name = "ronin-all"
version = "0.0.0"
publish = false
authors = ["Asteria <asteria@syvita.org>"]

[workspace]
members = [
    "api", "node"
]
default_members = [
    "api", "node/testnet/stacks-node"
]

